// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tpetl_abdarrahmane.filtre_subventions_data_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.TalendDate;
import routines.Relational;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: filtre_subventions_data Purpose: extration des données<br>
 * Description: un job pour extraire les données dans les fichiers CSV. <br>
 * 
 * @author user@talend.com
 * @version 8.0.1.20211109_1610
 * @status
 */
public class filtre_subventions_data implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

		// if the stored or passed value is "<TALEND_NULL>" string, it mean null
		public String getStringValue(String key) {
			String origin_value = this.getProperty(key);
			if (NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY.equals(origin_value)) {
				return null;
			}
			return origin_value;
		}

	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "filtre_subventions_data";
	private final String projectName = "TPETL_ABDARRAHMANE";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	public void setDataSourceReferences(List serviceReferences) throws Exception {

		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		java.util.Map<String, javax.sql.DataSource> dataSources = new java.util.HashMap<String, javax.sql.DataSource>();

		for (java.util.Map.Entry<String, javax.sql.DataSource> entry : BundleUtils
				.getServices(serviceReferences, javax.sql.DataSource.class).entrySet()) {
			dataSources.put(entry.getKey(), entry.getValue());
			talendDataSources.put(entry.getKey(), new routines.system.TalendDataSource(entry.getValue()));
		}

		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					filtre_subventions_data.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(filtre_subventions_data.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tFileInputDelimited_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFileInputDelimited_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_3_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFileInputDelimited_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFileInputDelimited_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileInputDelimited_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class subvention_validStruct implements routines.system.IPersistableRow<subvention_validStruct> {
		final static byte[] commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[0];
		static byte[] commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[0];

		public String MILLESIME;

		public String getMILLESIME() {
			return this.MILLESIME;
		}

		public String LIB;

		public String getLIB() {
			return this.LIB;
		}

		public String Minist_re;

		public String getMinist_re() {
			return this.Minist_re;
		}

		public String PROGRAMME;

		public String getPROGRAMME() {
			return this.PROGRAMME;
		}

		public String ASSOCIATION;

		public String getASSOCIATION() {
			return this.ASSOCIATION;
		}

		public Integer SIREN;

		public Integer getSIREN() {
			return this.SIREN;
		}

		public Integer DEPARTEMENT;

		public Integer getDEPARTEMENT() {
			return this.DEPARTEMENT;
		}

		public String VILLE;

		public String getVILLE() {
			return this.VILLE;
		}

		public String Subvention_2012;

		public String getSubvention_2012() {
			return this.Subvention_2012;
		}

		public String OBJET;

		public String getOBJET() {
			return this.OBJET;
		}

		public String EVALUATION;

		public String getEVALUATION() {
			return this.EVALUATION;
		}

		public String Convention;

		public String getConvention() {
			return this.Convention;
		}

		public String El_ments_de_la_convention;

		public String getEl_ments_de_la_convention() {
			return this.El_ments_de_la_convention;
		}

		public String Mission;

		public String getMission() {
			return this.Mission;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length) {
					if (length < 1024 && commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length == 0) {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[1024];
					} else {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length);
				strReturn = new String(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length) {
					if (length < 1024 && commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length == 0) {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[1024];
					} else {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length);
				strReturn = new String(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private Integer readInteger(org.jboss.marshalling.Unmarshaller dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos) throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		private void writeInteger(Integer intNum, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (intNum == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data) {

				try {

					int length = 0;

					this.MILLESIME = readString(dis);

					this.LIB = readString(dis);

					this.Minist_re = readString(dis);

					this.PROGRAMME = readString(dis);

					this.ASSOCIATION = readString(dis);

					this.SIREN = readInteger(dis);

					this.DEPARTEMENT = readInteger(dis);

					this.VILLE = readString(dis);

					this.Subvention_2012 = readString(dis);

					this.OBJET = readString(dis);

					this.EVALUATION = readString(dis);

					this.Convention = readString(dis);

					this.El_ments_de_la_convention = readString(dis);

					this.Mission = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data) {

				try {

					int length = 0;

					this.MILLESIME = readString(dis);

					this.LIB = readString(dis);

					this.Minist_re = readString(dis);

					this.PROGRAMME = readString(dis);

					this.ASSOCIATION = readString(dis);

					this.SIREN = readInteger(dis);

					this.DEPARTEMENT = readInteger(dis);

					this.VILLE = readString(dis);

					this.Subvention_2012 = readString(dis);

					this.OBJET = readString(dis);

					this.EVALUATION = readString(dis);

					this.Convention = readString(dis);

					this.El_ments_de_la_convention = readString(dis);

					this.Mission = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.MILLESIME, dos);

				// String

				writeString(this.LIB, dos);

				// String

				writeString(this.Minist_re, dos);

				// String

				writeString(this.PROGRAMME, dos);

				// String

				writeString(this.ASSOCIATION, dos);

				// Integer

				writeInteger(this.SIREN, dos);

				// Integer

				writeInteger(this.DEPARTEMENT, dos);

				// String

				writeString(this.VILLE, dos);

				// String

				writeString(this.Subvention_2012, dos);

				// String

				writeString(this.OBJET, dos);

				// String

				writeString(this.EVALUATION, dos);

				// String

				writeString(this.Convention, dos);

				// String

				writeString(this.El_ments_de_la_convention, dos);

				// String

				writeString(this.Mission, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// String

				writeString(this.MILLESIME, dos);

				// String

				writeString(this.LIB, dos);

				// String

				writeString(this.Minist_re, dos);

				// String

				writeString(this.PROGRAMME, dos);

				// String

				writeString(this.ASSOCIATION, dos);

				// Integer

				writeInteger(this.SIREN, dos);

				// Integer

				writeInteger(this.DEPARTEMENT, dos);

				// String

				writeString(this.VILLE, dos);

				// String

				writeString(this.Subvention_2012, dos);

				// String

				writeString(this.OBJET, dos);

				// String

				writeString(this.EVALUATION, dos);

				// String

				writeString(this.Convention, dos);

				// String

				writeString(this.El_ments_de_la_convention, dos);

				// String

				writeString(this.Mission, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("MILLESIME=" + MILLESIME);
			sb.append(",LIB=" + LIB);
			sb.append(",Minist_re=" + Minist_re);
			sb.append(",PROGRAMME=" + PROGRAMME);
			sb.append(",ASSOCIATION=" + ASSOCIATION);
			sb.append(",SIREN=" + String.valueOf(SIREN));
			sb.append(",DEPARTEMENT=" + String.valueOf(DEPARTEMENT));
			sb.append(",VILLE=" + VILLE);
			sb.append(",Subvention_2012=" + Subvention_2012);
			sb.append(",OBJET=" + OBJET);
			sb.append(",EVALUATION=" + EVALUATION);
			sb.append(",Convention=" + Convention);
			sb.append(",El_ments_de_la_convention=" + El_ments_de_la_convention);
			sb.append(",Mission=" + Mission);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(subvention_validStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[0];
		static byte[] commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[0];

		public String MILLESIME;

		public String getMILLESIME() {
			return this.MILLESIME;
		}

		public String LIB;

		public String getLIB() {
			return this.LIB;
		}

		public String Minist_re;

		public String getMinist_re() {
			return this.Minist_re;
		}

		public String PROGRAMME;

		public String getPROGRAMME() {
			return this.PROGRAMME;
		}

		public String ASSOCIATION;

		public String getASSOCIATION() {
			return this.ASSOCIATION;
		}

		public Integer SIREN;

		public Integer getSIREN() {
			return this.SIREN;
		}

		public Integer DEPARTEMENT;

		public Integer getDEPARTEMENT() {
			return this.DEPARTEMENT;
		}

		public String VILLE;

		public String getVILLE() {
			return this.VILLE;
		}

		public String Subvention_2012;

		public String getSubvention_2012() {
			return this.Subvention_2012;
		}

		public String OBJET;

		public String getOBJET() {
			return this.OBJET;
		}

		public String EVALUATION;

		public String getEVALUATION() {
			return this.EVALUATION;
		}

		public String Convention;

		public String getConvention() {
			return this.Convention;
		}

		public String El_ments_de_la_convention;

		public String getEl_ments_de_la_convention() {
			return this.El_ments_de_la_convention;
		}

		public String Mission;

		public String getMission() {
			return this.Mission;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length) {
					if (length < 1024 && commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length == 0) {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[1024];
					} else {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length);
				strReturn = new String(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length) {
					if (length < 1024 && commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data.length == 0) {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[1024];
					} else {
						commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length);
				strReturn = new String(commonByteArray_TPETL_ABDARRAHMANE_filtre_subventions_data, 0, length,
						utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private Integer readInteger(org.jboss.marshalling.Unmarshaller dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos) throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		private void writeInteger(Integer intNum, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (intNum == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeInt(intNum);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data) {

				try {

					int length = 0;

					this.MILLESIME = readString(dis);

					this.LIB = readString(dis);

					this.Minist_re = readString(dis);

					this.PROGRAMME = readString(dis);

					this.ASSOCIATION = readString(dis);

					this.SIREN = readInteger(dis);

					this.DEPARTEMENT = readInteger(dis);

					this.VILLE = readString(dis);

					this.Subvention_2012 = readString(dis);

					this.OBJET = readString(dis);

					this.EVALUATION = readString(dis);

					this.Convention = readString(dis);

					this.El_ments_de_la_convention = readString(dis);

					this.Mission = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_TPETL_ABDARRAHMANE_filtre_subventions_data) {

				try {

					int length = 0;

					this.MILLESIME = readString(dis);

					this.LIB = readString(dis);

					this.Minist_re = readString(dis);

					this.PROGRAMME = readString(dis);

					this.ASSOCIATION = readString(dis);

					this.SIREN = readInteger(dis);

					this.DEPARTEMENT = readInteger(dis);

					this.VILLE = readString(dis);

					this.Subvention_2012 = readString(dis);

					this.OBJET = readString(dis);

					this.EVALUATION = readString(dis);

					this.Convention = readString(dis);

					this.El_ments_de_la_convention = readString(dis);

					this.Mission = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// String

				writeString(this.MILLESIME, dos);

				// String

				writeString(this.LIB, dos);

				// String

				writeString(this.Minist_re, dos);

				// String

				writeString(this.PROGRAMME, dos);

				// String

				writeString(this.ASSOCIATION, dos);

				// Integer

				writeInteger(this.SIREN, dos);

				// Integer

				writeInteger(this.DEPARTEMENT, dos);

				// String

				writeString(this.VILLE, dos);

				// String

				writeString(this.Subvention_2012, dos);

				// String

				writeString(this.OBJET, dos);

				// String

				writeString(this.EVALUATION, dos);

				// String

				writeString(this.Convention, dos);

				// String

				writeString(this.El_ments_de_la_convention, dos);

				// String

				writeString(this.Mission, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// String

				writeString(this.MILLESIME, dos);

				// String

				writeString(this.LIB, dos);

				// String

				writeString(this.Minist_re, dos);

				// String

				writeString(this.PROGRAMME, dos);

				// String

				writeString(this.ASSOCIATION, dos);

				// Integer

				writeInteger(this.SIREN, dos);

				// Integer

				writeInteger(this.DEPARTEMENT, dos);

				// String

				writeString(this.VILLE, dos);

				// String

				writeString(this.Subvention_2012, dos);

				// String

				writeString(this.OBJET, dos);

				// String

				writeString(this.EVALUATION, dos);

				// String

				writeString(this.Convention, dos);

				// String

				writeString(this.El_ments_de_la_convention, dos);

				// String

				writeString(this.Mission, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("MILLESIME=" + MILLESIME);
			sb.append(",LIB=" + LIB);
			sb.append(",Minist_re=" + Minist_re);
			sb.append(",PROGRAMME=" + PROGRAMME);
			sb.append(",ASSOCIATION=" + ASSOCIATION);
			sb.append(",SIREN=" + String.valueOf(SIREN));
			sb.append(",DEPARTEMENT=" + String.valueOf(DEPARTEMENT));
			sb.append(",VILLE=" + VILLE);
			sb.append(",Subvention_2012=" + Subvention_2012);
			sb.append(",OBJET=" + OBJET);
			sb.append(",EVALUATION=" + EVALUATION);
			sb.append(",Convention=" + Convention);
			sb.append(",El_ments_de_la_convention=" + El_ments_de_la_convention);
			sb.append(",Mission=" + Mission);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tFileInputDelimited_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tFileInputDelimited_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				subvention_validStruct subvention_valid = new subvention_validStruct();

				/**
				 * [tLogRow_1 begin ] start
				 */

				ok_Hash.put("tLogRow_1", false);
				start_Hash.put("tLogRow_1", System.currentTimeMillis());

				currentComponent = "tLogRow_1";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "subvention_valid");
				}

				int tos_count_tLogRow_1 = 0;

				///////////////////////

				class Util_tLogRow_1 {

					String[] des_top = { ".", "-" };

					String[] des_data = { "-", "+" };

					String[] des_frame = { "|" };

					public void printLine(StringBuilder sb, int titleWidth, int dataWidth) {

						sb.append("+");
						for (int i = 0; i < titleWidth + 2; i++)
							sb.append("-");
						sb.append("+");
						for (int i = 0; i < dataWidth + 2; i++)
							sb.append("-");
						sb.append("+" + "\n");
					}

					public String print(String[] row, int nbLine) {

						StringBuilder sb = new StringBuilder();

						String title = "#" + nbLine + ". " + "tLogRow_1";

						// step 1: get the max length of all the row[] member;
						int dataWidth = 5; // the length of the string "value"
						for (int i = 0; i < row.length; i++) {
							if (row[i] == null && 4 > dataWidth) {
								dataWidth = 4;
							} else if (row[i] != null && row[i].length() > dataWidth)
								dataWidth = row[i].length();
						}

						int titleWidth = 25;

						int totalWidth = dataWidth + titleWidth + 5;

						// step 2: print the header with line number
						sb.append(".");
						for (int i = 0; i < totalWidth; i++)
							sb.append("-");
						sb.append("." + "\n" + "|");

						int emptyCenterWidth = (totalWidth - title.length()) / 2;
						for (int i = 0; i < emptyCenterWidth; i++)
							sb.append(" ");
						sb.append(title);
						for (int i = 0; i < totalWidth - emptyCenterWidth - title.length(); i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// step 3: print "key" and "value"
						printLine(sb, titleWidth, dataWidth);

						sb.append("|" + " key");
						for (int i = 0; i < titleWidth - 2; i++)
							sb.append(" ");
						sb.append("|" + " value");
						for (int i = 0; i < dataWidth - 4; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						printLine(sb, titleWidth, dataWidth);

						// step 4: print dataset

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "MILLESIME");
						for (int i = 0; i < titleWidth - "MILLESIME".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[0]);
						for (int i = 0; row[0] == null && i < dataWidth - 3
								|| row[0] != null && i < dataWidth - row[0].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "LIB");
						for (int i = 0; i < titleWidth - "LIB".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[1]);
						for (int i = 0; row[1] == null && i < dataWidth - 3
								|| row[1] != null && i < dataWidth - row[1].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "Minist_re");
						for (int i = 0; i < titleWidth - "Minist_re".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[2]);
						for (int i = 0; row[2] == null && i < dataWidth - 3
								|| row[2] != null && i < dataWidth - row[2].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "PROGRAMME");
						for (int i = 0; i < titleWidth - "PROGRAMME".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[3]);
						for (int i = 0; row[3] == null && i < dataWidth - 3
								|| row[3] != null && i < dataWidth - row[3].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "ASSOCIATION");
						for (int i = 0; i < titleWidth - "ASSOCIATION".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[4]);
						for (int i = 0; row[4] == null && i < dataWidth - 3
								|| row[4] != null && i < dataWidth - row[4].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "SIREN");
						for (int i = 0; i < titleWidth - "SIREN".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[5]);
						for (int i = 0; row[5] == null && i < dataWidth - 3
								|| row[5] != null && i < dataWidth - row[5].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "DEPARTEMENT");
						for (int i = 0; i < titleWidth - "DEPARTEMENT".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[6]);
						for (int i = 0; row[6] == null && i < dataWidth - 3
								|| row[6] != null && i < dataWidth - row[6].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "VILLE");
						for (int i = 0; i < titleWidth - "VILLE".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[7]);
						for (int i = 0; row[7] == null && i < dataWidth - 3
								|| row[7] != null && i < dataWidth - row[7].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "Subvention_2012");
						for (int i = 0; i < titleWidth - "Subvention_2012".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[8]);
						for (int i = 0; row[8] == null && i < dataWidth - 3
								|| row[8] != null && i < dataWidth - row[8].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "OBJET");
						for (int i = 0; i < titleWidth - "OBJET".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[9]);
						for (int i = 0; row[9] == null && i < dataWidth - 3
								|| row[9] != null && i < dataWidth - row[9].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "EVALUATION");
						for (int i = 0; i < titleWidth - "EVALUATION".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[10]);
						for (int i = 0; row[10] == null && i < dataWidth - 3
								|| row[10] != null && i < dataWidth - row[10].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "Convention");
						for (int i = 0; i < titleWidth - "Convention".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[11]);
						for (int i = 0; row[11] == null && i < dataWidth - 3
								|| row[11] != null && i < dataWidth - row[11].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "El_ments_de_la_convention");
						for (int i = 0; i < titleWidth - "El_ments_de_la_convention".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[12]);
						for (int i = 0; row[12] == null && i < dataWidth - 3
								|| row[12] != null && i < dataWidth - row[12].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// for(int i=0; i<row.length; i++){
						sb.append("| " + "Mission");
						for (int i = 0; i < titleWidth - "Mission".length() + 1; i++)
							sb.append(" ");
						sb.append("| " + row[13]);
						for (int i = 0; row[13] == null && i < dataWidth - 3
								|| row[13] != null && i < dataWidth - row[13].length() + 1; i++)
							sb.append(" ");
						sb.append("|" + "\n");

						// }

						// step 5: print a line gap
						printLine(sb, titleWidth, dataWidth);
						return sb.toString();

					}

				}

				Util_tLogRow_1 util_tLogRow_1 = new Util_tLogRow_1();

				java.io.PrintStream consoleOut_tLogRow_1 = null;
				if (globalMap.get("tLogRow_CONSOLE") != null) {
					consoleOut_tLogRow_1 = (java.io.PrintStream) globalMap.get("tLogRow_CONSOLE");
				} else {
					consoleOut_tLogRow_1 = new java.io.PrintStream(new java.io.BufferedOutputStream(System.out));
					globalMap.put("tLogRow_CONSOLE", consoleOut_tLogRow_1);
				}

				StringBuilder strBuffer_tLogRow_1 = null;
				int nb_line_tLogRow_1 = 0;
///////////////////////    			

				/**
				 * [tLogRow_1 begin ] stop
				 */

				/**
				 * [tMap_3 begin ] start
				 */

				ok_Hash.put("tMap_3", false);
				start_Hash.put("tMap_3", System.currentTimeMillis());

				currentComponent = "tMap_3";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "row1");
				}

				int tos_count_tMap_3 = 0;

// ###############################
// # Lookup's keys initialization
// ###############################        

// ###############################
// # Vars initialization
				class Var__tMap_3__Struct {
				}
				Var__tMap_3__Struct Var__tMap_3 = new Var__tMap_3__Struct();
// ###############################

// ###############################
// # Outputs initialization
				subvention_validStruct subvention_valid_tmp = new subvention_validStruct();
// ###############################

				/**
				 * [tMap_3 begin ] stop
				 */

				/**
				 * [tFileInputDelimited_1 begin ] start
				 */

				ok_Hash.put("tFileInputDelimited_1", false);
				start_Hash.put("tFileInputDelimited_1", System.currentTimeMillis());

				currentComponent = "tFileInputDelimited_1";

				int tos_count_tFileInputDelimited_1 = 0;

				final routines.system.RowState rowstate_tFileInputDelimited_1 = new routines.system.RowState();

				int nb_line_tFileInputDelimited_1 = 0;
				org.talend.fileprocess.FileInputDelimited fid_tFileInputDelimited_1 = null;
				int limit_tFileInputDelimited_1 = -1;
				try {

					Object filename_tFileInputDelimited_1 = "/Users/abdarrahmane/Downloads/plf-2014-jaune-associations-subventionne-es-2012.csv";
					if (filename_tFileInputDelimited_1 instanceof java.io.InputStream) {

						int footer_value_tFileInputDelimited_1 = 0, random_value_tFileInputDelimited_1 = -1;
						if (footer_value_tFileInputDelimited_1 > 0 || random_value_tFileInputDelimited_1 > 0) {
							throw new java.lang.Exception(
									"When the input source is a stream,footer and random shouldn't be bigger than 0.");
						}

					}
					try {
						fid_tFileInputDelimited_1 = new org.talend.fileprocess.FileInputDelimited(
								"/Users/abdarrahmane/Downloads/plf-2014-jaune-associations-subventionne-es-2012.csv",
								"UTF-8", ";", "\r", false, 1, 0, limit_tFileInputDelimited_1, -1, false);
					} catch (java.lang.Exception e) {
						globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE", e.getMessage());

						System.err.println(e.getMessage());

					}

					while (fid_tFileInputDelimited_1 != null && fid_tFileInputDelimited_1.nextRecord()) {
						rowstate_tFileInputDelimited_1.reset();

						row1 = null;

						boolean whetherReject_tFileInputDelimited_1 = false;
						row1 = new row1Struct();
						try {

							int columnIndexWithD_tFileInputDelimited_1 = 0;

							String temp = "";

							columnIndexWithD_tFileInputDelimited_1 = 0;

							row1.MILLESIME = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 1;

							row1.LIB = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 2;

							row1.Minist_re = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 3;

							row1.PROGRAMME = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 4;

							row1.ASSOCIATION = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 5;

							temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
							if (temp.length() > 0) {

								try {

									row1.SIREN = ParserUtils.parseTo_Integer(temp);

								} catch (java.lang.Exception ex_tFileInputDelimited_1) {
									globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
											ex_tFileInputDelimited_1.getMessage());
									rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
											"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
											"SIREN", "row1", temp, ex_tFileInputDelimited_1),
											ex_tFileInputDelimited_1));
								}

							} else {

								row1.SIREN = null;

							}

							columnIndexWithD_tFileInputDelimited_1 = 6;

							temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
							if (temp.length() > 0) {

								try {

									row1.DEPARTEMENT = ParserUtils.parseTo_Integer(temp);

								} catch (java.lang.Exception ex_tFileInputDelimited_1) {
									globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
											ex_tFileInputDelimited_1.getMessage());
									rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
											"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
											"DEPARTEMENT", "row1", temp, ex_tFileInputDelimited_1),
											ex_tFileInputDelimited_1));
								}

							} else {

								row1.DEPARTEMENT = null;

							}

							columnIndexWithD_tFileInputDelimited_1 = 7;

							row1.VILLE = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 8;

							row1.Subvention_2012 = fid_tFileInputDelimited_1
									.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 9;

							row1.OBJET = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 10;

							row1.EVALUATION = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 11;

							row1.Convention = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 12;

							row1.El_ments_de_la_convention = fid_tFileInputDelimited_1
									.get(columnIndexWithD_tFileInputDelimited_1);

							columnIndexWithD_tFileInputDelimited_1 = 13;

							row1.Mission = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);

							if (rowstate_tFileInputDelimited_1.getException() != null) {
								throw rowstate_tFileInputDelimited_1.getException();
							}

						} catch (java.lang.Exception e) {
							globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE", e.getMessage());
							whetherReject_tFileInputDelimited_1 = true;

							System.err.println(e.getMessage());
							row1 = null;

						}

						/**
						 * [tFileInputDelimited_1 begin ] stop
						 */

						/**
						 * [tFileInputDelimited_1 main ] start
						 */

						currentComponent = "tFileInputDelimited_1";

						tos_count_tFileInputDelimited_1++;

						/**
						 * [tFileInputDelimited_1 main ] stop
						 */

						/**
						 * [tFileInputDelimited_1 process_data_begin ] start
						 */

						currentComponent = "tFileInputDelimited_1";

						/**
						 * [tFileInputDelimited_1 process_data_begin ] stop
						 */
// Start of branch "row1"
						if (row1 != null) {

							/**
							 * [tMap_3 main ] start
							 */

							currentComponent = "tMap_3";

							if (execStat) {
								runStat.updateStatOnConnection(iterateId, 1, 1

										, "row1"

								);
							}

							boolean hasCasePrimitiveKeyWithNull_tMap_3 = false;

							// ###############################
							// # Input tables (lookups)
							boolean rejectedInnerJoin_tMap_3 = false;
							boolean mainRowRejected_tMap_3 = false;

							// ###############################
							{ // start of Var scope

								// ###############################
								// # Vars tables

								Var__tMap_3__Struct Var = Var__tMap_3;// ###############################
								// ###############################
								// # Output tables

								subvention_valid = null;

// # Output table : 'subvention_valid'
								subvention_valid_tmp.MILLESIME = row1.MILLESIME;
								subvention_valid_tmp.LIB = row1.LIB;
								subvention_valid_tmp.Minist_re = row1.Minist_re;
								subvention_valid_tmp.PROGRAMME = row1.PROGRAMME;
								subvention_valid_tmp.ASSOCIATION = row1.ASSOCIATION;
								subvention_valid_tmp.SIREN = row1.SIREN;
								subvention_valid_tmp.DEPARTEMENT = row1.DEPARTEMENT;
								subvention_valid_tmp.VILLE = row1.VILLE;
								subvention_valid_tmp.Subvention_2012 = row1.Subvention_2012;
								subvention_valid_tmp.OBJET = row1.OBJET;
								subvention_valid_tmp.EVALUATION = row1.EVALUATION;
								subvention_valid_tmp.Convention = row1.Convention;
								subvention_valid_tmp.El_ments_de_la_convention = row1.El_ments_de_la_convention;
								subvention_valid_tmp.Mission = row1.Mission;
								subvention_valid = subvention_valid_tmp;
// ###############################

							} // end of Var scope

							rejectedInnerJoin_tMap_3 = false;

							tos_count_tMap_3++;

							/**
							 * [tMap_3 main ] stop
							 */

							/**
							 * [tMap_3 process_data_begin ] start
							 */

							currentComponent = "tMap_3";

							/**
							 * [tMap_3 process_data_begin ] stop
							 */
// Start of branch "subvention_valid"
							if (subvention_valid != null) {

								/**
								 * [tLogRow_1 main ] start
								 */

								currentComponent = "tLogRow_1";

								if (execStat) {
									runStat.updateStatOnConnection(iterateId, 1, 1

											, "subvention_valid"

									);
								}

///////////////////////		

								strBuffer_tLogRow_1 = new StringBuilder();

								if (subvention_valid.MILLESIME != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.MILLESIME));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.LIB != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.LIB));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.Minist_re != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.Minist_re));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.PROGRAMME != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.PROGRAMME));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.ASSOCIATION != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.ASSOCIATION));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.SIREN != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.SIREN));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.DEPARTEMENT != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.DEPARTEMENT));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.VILLE != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.VILLE));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.Subvention_2012 != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.Subvention_2012));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.OBJET != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.OBJET));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.EVALUATION != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.EVALUATION));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.Convention != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.Convention));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.El_ments_de_la_convention != null) { //

									strBuffer_tLogRow_1
											.append(String.valueOf(subvention_valid.El_ments_de_la_convention));

								} //

								strBuffer_tLogRow_1.append("|");

								if (subvention_valid.Mission != null) { //

									strBuffer_tLogRow_1.append(String.valueOf(subvention_valid.Mission));

								} //

								String[] row_tLogRow_1 = new String[14];

								if (subvention_valid.MILLESIME != null) { //
									row_tLogRow_1[0] = String.valueOf(subvention_valid.MILLESIME);

								} //

								if (subvention_valid.LIB != null) { //
									row_tLogRow_1[1] = String.valueOf(subvention_valid.LIB);

								} //

								if (subvention_valid.Minist_re != null) { //
									row_tLogRow_1[2] = String.valueOf(subvention_valid.Minist_re);

								} //

								if (subvention_valid.PROGRAMME != null) { //
									row_tLogRow_1[3] = String.valueOf(subvention_valid.PROGRAMME);

								} //

								if (subvention_valid.ASSOCIATION != null) { //
									row_tLogRow_1[4] = String.valueOf(subvention_valid.ASSOCIATION);

								} //

								if (subvention_valid.SIREN != null) { //
									row_tLogRow_1[5] = String.valueOf(subvention_valid.SIREN);

								} //

								if (subvention_valid.DEPARTEMENT != null) { //
									row_tLogRow_1[6] = String.valueOf(subvention_valid.DEPARTEMENT);

								} //

								if (subvention_valid.VILLE != null) { //
									row_tLogRow_1[7] = String.valueOf(subvention_valid.VILLE);

								} //

								if (subvention_valid.Subvention_2012 != null) { //
									row_tLogRow_1[8] = String.valueOf(subvention_valid.Subvention_2012);

								} //

								if (subvention_valid.OBJET != null) { //
									row_tLogRow_1[9] = String.valueOf(subvention_valid.OBJET);

								} //

								if (subvention_valid.EVALUATION != null) { //
									row_tLogRow_1[10] = String.valueOf(subvention_valid.EVALUATION);

								} //

								if (subvention_valid.Convention != null) { //
									row_tLogRow_1[11] = String.valueOf(subvention_valid.Convention);

								} //

								if (subvention_valid.El_ments_de_la_convention != null) { //
									row_tLogRow_1[12] = String.valueOf(subvention_valid.El_ments_de_la_convention);

								} //

								if (subvention_valid.Mission != null) { //
									row_tLogRow_1[13] = String.valueOf(subvention_valid.Mission);

								} //

								nb_line_tLogRow_1++;
								consoleOut_tLogRow_1.println(util_tLogRow_1.print(row_tLogRow_1, nb_line_tLogRow_1));
								consoleOut_tLogRow_1.flush();
//////

//////                    

///////////////////////    			

								tos_count_tLogRow_1++;

								/**
								 * [tLogRow_1 main ] stop
								 */

								/**
								 * [tLogRow_1 process_data_begin ] start
								 */

								currentComponent = "tLogRow_1";

								/**
								 * [tLogRow_1 process_data_begin ] stop
								 */

								/**
								 * [tLogRow_1 process_data_end ] start
								 */

								currentComponent = "tLogRow_1";

								/**
								 * [tLogRow_1 process_data_end ] stop
								 */

							} // End of branch "subvention_valid"

							/**
							 * [tMap_3 process_data_end ] start
							 */

							currentComponent = "tMap_3";

							/**
							 * [tMap_3 process_data_end ] stop
							 */

						} // End of branch "row1"

						/**
						 * [tFileInputDelimited_1 process_data_end ] start
						 */

						currentComponent = "tFileInputDelimited_1";

						/**
						 * [tFileInputDelimited_1 process_data_end ] stop
						 */

						/**
						 * [tFileInputDelimited_1 end ] start
						 */

						currentComponent = "tFileInputDelimited_1";

					}
				} finally {
					if (!((Object) ("/Users/abdarrahmane/Downloads/plf-2014-jaune-associations-subventionne-es-2012.csv") instanceof java.io.InputStream)) {
						if (fid_tFileInputDelimited_1 != null) {
							fid_tFileInputDelimited_1.close();
						}
					}
					if (fid_tFileInputDelimited_1 != null) {
						globalMap.put("tFileInputDelimited_1_NB_LINE", fid_tFileInputDelimited_1.getRowNumber());

					}
				}

				ok_Hash.put("tFileInputDelimited_1", true);
				end_Hash.put("tFileInputDelimited_1", System.currentTimeMillis());

				/**
				 * [tFileInputDelimited_1 end ] stop
				 */

				/**
				 * [tMap_3 end ] start
				 */

				currentComponent = "tMap_3";

// ###############################
// # Lookup hashes releasing
// ###############################      

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "row1");
				}

				ok_Hash.put("tMap_3", true);
				end_Hash.put("tMap_3", System.currentTimeMillis());

				/**
				 * [tMap_3 end ] stop
				 */

				/**
				 * [tLogRow_1 end ] start
				 */

				currentComponent = "tLogRow_1";

//////
//////
				globalMap.put("tLogRow_1_NB_LINE", nb_line_tLogRow_1);

///////////////////////    			

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "subvention_valid");
				}

				ok_Hash.put("tLogRow_1", true);
				end_Hash.put("tLogRow_1", System.currentTimeMillis());

				/**
				 * [tLogRow_1 end ] stop
				 */

			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFileInputDelimited_1 finally ] start
				 */

				currentComponent = "tFileInputDelimited_1";

				/**
				 * [tFileInputDelimited_1 finally ] stop
				 */

				/**
				 * [tMap_3 finally ] start
				 */

				currentComponent = "tMap_3";

				/**
				 * [tMap_3 finally ] stop
				 */

				/**
				 * [tLogRow_1 finally ] start
				 */

				currentComponent = "tLogRow_1";

				/**
				 * [tLogRow_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFileInputDelimited_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean enableLogStash;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	protected PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final filtre_subventions_data filtre_subventions_dataClass = new filtre_subventions_data();

		int exitCode = filtre_subventions_dataClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}
		enableLogStash = "true".equalsIgnoreCase(System.getProperty("audit.enabled"));

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}
		boolean inOSGi = routines.system.BundleUtils.inOSGi();

		if (inOSGi) {
			java.util.Dictionary<String, Object> jobProperties = routines.system.BundleUtils.getJobProperties(jobName);

			if (jobProperties != null && jobProperties.get("context") != null) {
				contextStr = (String) jobProperties.get("context");
			}
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = filtre_subventions_data.class.getClassLoader().getResourceAsStream(
					"tpetl_abdarrahmane/filtre_subventions_data_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = filtre_subventions_data.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				try {
					// defaultProps is in order to keep the original context value
					if (context != null && context.isEmpty()) {
						defaultProps.load(inContext);
						context = new ContextProperties(defaultProps);
					}
				} finally {
					inContext.close();
				}
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tFileInputDelimited_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tFileInputDelimited_1) {
			globalMap.put("tFileInputDelimited_1_SUBPROCESS_STATE", -1);

			e_tFileInputDelimited_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println((endUsedMemory - startUsedMemory)
					+ " bytes memory increase when running : filtre_subventions_data");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;

		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--audit.enabled") && arg.contains("=")) {// for trunjob call
			final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 75380 characters generated by Talend Open Studio for Data Integration on the
 * July 13, 2022 at 7:14:14 PM CEST
 ************************************************************************************************/